name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

resources:
  - repo: self

parameters:
  - name: sonarProjectName
    type: string    

  - name: projectName
    type: string    

  - name: buildPlatform
    type: string
    default: any cpu

  - name: buildConfiguration
    type: string
    default: release

  - name: solutionPath
    type: string
    default: "**/*.sln"

jobs:
  - job:
    displayName: Build

    variables:
      slnFileName: ${{ parameters.projectName }}.sln
      apiProjectName: ${{ parameters.projectName }}.Service
      apiPackageId: ${{ parameters.projectName }}
      apiPackageTitle: ${{ parameters.projectName }}
      apiPackageDescription: ${{ parameters.projectName }}
      clientProjectName: ${{ parameters.projectName }}.Client
      contractsProjectName: ${{ parameters.projectName }}.DataContracts

    pool:
      vmImage: 'ubuntu-latest'
      demands:
        - msbuild
        - visualstudio
        - DotNetFramework
        - vstest
        - java

    steps:
      - template: steps/build-and-test.yaml
        parameters:
          sonarProjectName: ${{ parameters.sonarProjectName }}
          slnFileName: $(slnFileName)
          buildPlatform: ${{ parameters.buildPlatform }}
          buildConfiguration: ${{ parameters.buildConfiguration }}
          solutionPath: ${{ parameters.solutionPath }}

      - template: steps/create-install-package.yaml
        parameters:
          projectName: $(apiProjectName)
          packageId: $(apiPackageId)
          packageTitle: $(apiPackageTitle)
          packageDescription: $(apiPackageDescription)
          buildConfiguration: ${{ parameters.buildConfiguration }}

      - template: steps/create-shared-package.yaml
        parameters:
          clientProjectPath: $(clientProjectName)/$(clientProjectName).csproj
          contractsProjectPath: $(contractsProjectName)/$(contractsProjectName).csproj

      - template: steps/publish-packages-and-artifacts.yaml
